[package]
name = "rdd"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", default-features = false, features = ["stream", "http2", "rustls-tls"] }
tokio = { version = "1.37.0", default-features = false, features = ["rt", "fs"] }
tokio-stream = "0.1.15"
